server {
    listen 80;
    server_name localhost;

    # 1. Standardowe serwowanie Twojej strony (React)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. MAGIA REVERSE PROXY: Przechwytujemy zapytania do bazy
    location /api/ {
        # 'backend' to nazwa kontenera z pliku docker-compose.yml
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}