name: CI Backend

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Pobranie kodu z repozytorium
      uses: actions/checkout@v4

    - name: Konfiguracja środowiska .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' 

    - name: Pobranie pakietów
      run: dotnet restore

    - name: Budowanie kodu
      run: dotnet build --no-restore

    - name: Uruchomienie testów
      run: dotnet test --no-build --verbosity normal
