name: CI Frontend

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Cloning the code from the repository
      uses: actions/checkout@v4

    - name: Installing pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Configuring the Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
        cache-dependency-path: './frontend/pnpm-lock.yaml'

    - name: Installing dependencies
      run: pnpm install --frozen-lockfile

    - name: Checking the code (Linter)
      run: pnpm run lint 

    - name: Building the application
      run: pnpm run build
